version: "3.8"

services:
  db:
    container_name: todo_app_db
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - todo_app

  admin:
    container_name: todo_app_db_web_adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 7070:8080
    networks:
      - todo_app

  backend:
    container_name: todo_app_backend
    build: ./backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./data/store:/usr/local/bin/store
    networks:
      - todo_app

  frontend:
    container_name: todo_app_frontend
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3010:3000
    networks:
      - todo_app

networks:
  todo_app:
